services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
      - /container/cert:/certs
    command:
      --sslcert /certs/docker.crt
      --sslkey /certs/docker.key
volumes:
  portainer: